export { default as AccountForm } from '../..\\components\\AccountForm.vue'
export { default as AllProduct } from '../..\\components\\all-product.vue'
export { default as AuthorityForm } from '../..\\components\\AuthorityForm.vue'
export { default as BasicAlert } from '../..\\components\\BasicAlert.vue'
export { default as Brands } from '../..\\components\\brands.vue'
export { default as CancelTicketForm } from '../..\\components\\CancelTicketForm.vue'
export { default as CardDashBoard } from '../..\\components\\CardDashBoard.vue'
export { default as Carousel3d } from '../..\\components\\Carousel3d.vue'
export { default as CategoryForm } from '../..\\components\\CategoryForm.vue'
export { default as ComingSoon } from '../..\\components\\ComingSoon.vue'
export { default as CompanyForm } from '../..\\components\\CompanyForm.vue'
export { default as CurrencyForm } from '../..\\components\\CurrencyForm.vue'
export { default as DeliveryForm } from '../..\\components\\deliveryForm.vue'
export { default as DiaConfirm } from '../..\\components\\DiaConfirm.vue'
export { default as DiaImage } from '../..\\components\\DiaImage.vue'
export { default as DialogClassicMessage } from '../..\\components\\DialogClassicMessage.vue'
export { default as DiscountProductsCard } from '../..\\components\\discount-products-card.vue'
export { default as Footer } from '../..\\components\\footer.vue'
export { default as GanttChart } from '../..\\components\\GanttChart.vue'
export { default as GroupForm } from '../..\\components\\GroupForm.vue'
export { default as HotProductsCard } from '../..\\components\\hot-products-card.vue'
export { default as ImageDialog } from '../..\\components\\ImageDialog.vue'
export { default as LineChart } from '../..\\components\\LineChart.vue'
export { default as LoadingIndicator } from '../..\\components\\LoadingIndicator.vue'
export { default as LocationForm } from '../..\\components\\LocationForm.vue'
export { default as MenuHeaderForm } from '../..\\components\\MenuHeaderForm.vue'
export { default as MenuLineForm } from '../..\\components\\MenuLineForm.vue'
export { default as MyChart } from '../..\\components\\MyChart.vue'
export { default as NewProductsCard } from '../..\\components\\new-products-card.vue'
export { default as NewUpdateProduct } from '../..\\components\\new-update-product.vue'
export { default as NewComing } from '../..\\components\\NewComing.vue'
export { default as Notification } from '../..\\components\\Notification.vue'
export { default as NuxtLogo } from '../..\\components\\NuxtLogo.vue'
export { default as OrderDetail } from '../..\\components\\OrderDetail.vue'
export { default as OrderDetailPos } from '../..\\components\\OrderDetailPos.vue'
export { default as OrderDetailPosCRUD } from '../..\\components\\OrderDetailPosCRUD.vue'
export { default as OrderForm } from '../..\\components\\OrderForm.vue'
export { default as OrderHistoryList } from '../..\\components\\OrderHistoryList.vue'
export { default as OrderStatusForm } from '../..\\components\\OrderStatusForm.vue'
export { default as OrderSumaryCard } from '../..\\components\\orderSumaryCard.vue'
export { default as OrderSumaryCardPos } from '../..\\components\\orderSumaryCardPos.vue'
export { default as OrderSumaryCardV2 } from '../..\\components\\orderSumaryCardV2.vue'
export { default as PaymentForm } from '../..\\components\\PaymentForm.vue'
export { default as PriceListForm } from '../..\\components\\PriceListForm.vue'
export { default as PricingOption } from '../..\\components\\PricingOption.vue'
export { default as ProductCard } from '../..\\components\\ProductCard.vue'
export { default as PurchasingFormCRUD } from '../..\\components\\PurchasingFormCRUD.vue'
export { default as ReceivingFormCRUD } from '../..\\components\\ReceivingFormCRUD.vue'
export { default as ReservationForm } from '../..\\components\\ReservationForm.vue'
export { default as RiderFormCopy } from '../..\\components\\RiderForm-copy.vue'
export { default as RiderForm } from '../..\\components\\RiderForm.vue'
export { default as Settlement } from '../..\\components\\Settlement.vue'
export { default as ShippingForm } from '../..\\components\\ShippingForm.vue'
export { default as Slider } from '../..\\components\\slider.vue'
export { default as TerminalForm } from '../..\\components\\TerminalForm.vue'
export { default as TransferForm } from '../..\\components\\TransferForm.vue'
export { default as TransferViewForm } from '../..\\components\\TransferViewForm.vue'
export { default as Tutorial } from '../..\\components\\Tutorial.vue'
export { default as TutorialForm } from '../..\\components\\TutorialForm.vue'
export { default as UnitForm } from '../..\\components\\unitForm.vue'
export { default as UserForm } from '../..\\components\\UserForm.vue'
export { default as VendorForm } from '../..\\components\\VendorForm.vue'
export { default as VuetifyLogo } from '../..\\components\\VuetifyLogo.vue'
export { default as Wallet } from '../..\\components\\Wallet.vue'
export { default as WebCategoryForm } from '../..\\components\\WebCategoryForm.vue'
export { default as WebCategoryProductForm } from '../..\\components\\WebCategoryProductForm.vue'
export { default as WebProductCategoryForm } from '../..\\components\\WebProductCategoryForm.vue'
export { default as YoutubePlayer } from '../..\\components\\YoutubePlayer.vue'
export { default as AccountingApPayment } from '../..\\components\\accounting\\ApPayment.vue'
export { default as AccountingArReceivable } from '../..\\components\\accounting\\ArReceivable.vue'
export { default as AccountingGLForm } from '../..\\components\\accounting\\GLForm.vue'
export { default as CalendarMyCalendar } from '../..\\components\\calendar\\MyCalendar.vue'
export { default as CafePOSScreen } from '../..\\components\\CafePOSScreen\\index.vue'
export { default as CampaignForm } from '../..\\components\\campaign\\CampaignForm.vue'
export { default as CardCampaignCard } from '../..\\components\\card\\campaignCard.vue'
export { default as CardForm } from '../..\\components\\card\\cardForm.vue'
export { default as CustomerForm } from '../..\\components\\customer\\CustomerForm.vue'
export { default as CustomerList } from '../..\\components\\customer\\CustomerList.vue'
export { default as DashboardCardGrouping } from '../..\\components\\dashboard\\CardGrouping.vue'
export { default as DashboardCardOnTop } from '../..\\components\\dashboard\\CardOnTop.vue'
export { default as DialogsBottomAlert } from '../..\\components\\dialogs\\bottomAlert.vue'
export { default as Menu } from '../..\\components\\menu\\index.vue'
export { default as MenuOverview } from '../..\\components\\menuOverview\\index.vue'
export { default as MinistryDialog } from '../..\\components\\ministry\\MinistryDialog.vue'
export { default as MinistryViewDialog } from '../..\\components\\ministry\\MinistryViewDialog.vue'
export { default as MinStockCard } from '../..\\components\\minStockCard\\index.vue'
export { default as PaymentCard } from '../..\\components\\paymentCard\\index.vue'
export { default as PaymentQr } from '../..\\components\\payment_qr\\index.vue'
export { default as PoForm } from '../..\\components\\po\\PoForm.vue'
export { default as PosCateogoryList } from '../..\\components\\pos\\CateogoryList.vue'
export { default as ProductItem } from '../..\\components\\product\\Item.vue'
export { default as ProductCardPos } from '../..\\components\\product\\ProductCardPos.vue'
export { default as ProductForm } from '../..\\components\\product\\ProductForm.vue'
export { default as ProductFormCreate } from '../..\\components\\product\\ProductFormCreate.vue'
export { default as Quotation } from '../..\\components\\quotation\\index.vue'
export { default as ScheduleMonthTable } from '../..\\components\\schedule\\MonthTable.vue'
export { default as TimelineGianttTimeline } from '../..\\components\\timeline\\GianttTimeline.vue'
export { default as ApplicantsApplicantDialog } from '../..\\components\\applicants\\ApplicantDialog\\index.vue'
export { default as ApplicantsApplicantViewDialog } from '../..\\components\\applicants\\ApplicantViewDialog\\index.vue'
export { default as ApplicantsStatusUpdateDialog } from '../..\\components\\applicants\\StatusUpdateDialog\\index.vue'
export { default as BenefitMaintain } from '../..\\components\\benefit\\maintain\\index.vue'
export { default as BankBankAccount } from '../..\\components\\bank\\bankAccount\\index.vue'
export { default as BenefitView } from '../..\\components\\benefit\\view\\index.vue'
export { default as CAFECustomerDialog } from '../..\\components\\CAFE\\customerDialog\\index.vue'
export { default as CAFEPrintdialog } from '../..\\components\\CAFE\\printdialog\\index.vue'
export { default as CAFEPaymentDialogFront } from '../..\\components\\CAFE\\paymentDialogFront\\index.vue'
export { default as JobAdvertiseStatusUpdate } from '../..\\components\\jobAdvertise\\statusUpdate\\index.vue'
export { default as JobAdvertiseMaintain } from '../..\\components\\jobAdvertise\\maintain\\index.vue'
export { default as JobAdvertiseView } from '../..\\components\\jobAdvertise\\view\\index.vue'
export { default as JobFairJobBatch } from '../..\\components\\job_fair\\job_batch\\index.vue'
export { default as MAPaymentAuditDialog } from '../..\\components\\MA\\paymentAuditDialog\\index.vue'
export { default as MAPaymentAuditReportDialog } from '../..\\components\\MA\\paymentAuditReportDialog\\index.vue'
export { default as MAPaymentCompareDialog } from '../..\\components\\MA\\paymentCompareDialog\\index.vue'
export { default as MAPaymentComponentsBankAccountInfo } from '../..\\components\\MA\\paymentComponents\\BankAccountInfo.vue'
export { default as MAPaymentComponentsDateField } from '../..\\components\\MA\\paymentComponents\\DateField.vue'
export { default as MAPaymentComponentsDialogFooter } from '../..\\components\\MA\\paymentComponents\\DialogFooter.vue'
export { default as MAPaymentComponentsDialogHeader } from '../..\\components\\MA\\paymentComponents\\DialogHeader.vue'
export { default as MAPaymentComponentsFormSection } from '../..\\components\\MA\\paymentComponents\\FormSection.vue'
export { default as MAPaymentComponentsInputField } from '../..\\components\\MA\\paymentComponents\\InputField.vue'
export { default as MAPaymentComponentsLoadingState } from '../..\\components\\MA\\paymentComponents\\LoadingState.vue'
export { default as MAPaymentComponentsMinistryInfo } from '../..\\components\\MA\\paymentComponents\\MinistryInfo.vue'
export { default as MAPaymentComponentsSelectField } from '../..\\components\\MA\\paymentComponents\\SelectField.vue'
export { default as MAPaymentComponentsTextareaField } from '../..\\components\\MA\\paymentComponents\\TextareaField.vue'
export { default as MAPaymentComponentsValidationErrors } from '../..\\components\\MA\\paymentComponents\\ValidationErrors.vue'
export { default as MAPaymentDetailDialog } from '../..\\components\\MA\\paymentDetailDialog\\index.vue'
export { default as MAPaymentDialog } from '../..\\components\\MA\\paymentDialog\\index.vue'
export { default as MAPaymentVoucher } from '../..\\components\\MA\\paymentVoucher\\index.vue'
export { default as MARevenueTargetDialog } from '../..\\components\\MA\\revenueTargetDialog\\index.vue'
export { default as MASettlementDialog } from '../..\\components\\MA\\settlementDialog\\index.vue'
export { default as MASettlementViewDialog } from '../..\\components\\MA\\settlementViewDialog\\index.vue'
export { default as MASettlementVoucher } from '../..\\components\\MA\\settlementVoucher\\index.vue'
export { default as PosDialogsQuantityUpdateDialog } from '../..\\components\\pos\\dialogs\\QuantityUpdateDialog.vue'
export { default as AccountingApInvoice } from '../..\\components\\accounting\\ap\\invoice\\index.vue'
export { default as AccountingApSettlement } from '../..\\components\\accounting\\ap\\settlement\\index.vue'
export { default as JobFairAgencyMaintain } from '../..\\components\\job_fair\\agency\\maintain\\index.vue'
export { default as JobFairAgencyView } from '../..\\components\\job_fair\\agency\\view\\index.vue'
export { default as JobFairMouMaintain } from '../..\\components\\job_fair\\mou\\maintain\\index.vue'
export { default as AccountingApSettlementAudit } from '../..\\components\\accounting\\ap\\settlement\\audit\\index.vue'
export { default as AccountingApInvoiceAudit } from '../..\\components\\accounting\\ap\\invoice\\audit\\index.vue'
export { default as AccountingArInvoiceAudit } from '../..\\components\\accounting\\ar\\invoice\\audit\\index.vue'
export { default as AccountingArInvoiceMaintain } from '../..\\components\\accounting\\ar\\invoice\\maintain\\index.vue'
export { default as AccountingArInvoiceView } from '../..\\components\\accounting\\ar\\invoice\\view\\index.vue'
export { default as AccountingArReceiveMaintain } from '../..\\components\\accounting\\ar\\receive\\maintain\\index.vue'
export { default as AccountingArReceiveView } from '../..\\components\\accounting\\ar\\receive\\view\\index.vue'
export { default as AccountingApSettlementAuditView } from '../..\\components\\accounting\\ap\\settlement\\audit\\view\\index.vue'
export { default as AccountingApInvoiceAuditView } from '../..\\components\\accounting\\ap\\invoice\\audit\\view\\index.vue'
export { default as AccountingArInvoiceAuditView } from '../..\\components\\accounting\\ar\\invoice\\audit\\view\\index.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
